# based on https://github.com/geopandas/geopandas/blob/master/appveyor.yml
# https://github.com/jtwhite79/pyemu/blob/develop/appveyor.yml
environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON_VERSION: "3.8"
      MINICONDA: C:\Miniconda38-x64
      ENV_FILE: "ci/latest-python-flopy-develop.yml"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_VERSION: "3.7"
      MINICONDA: C:\Miniconda37-x64
      ENV_FILE: "ci/37-conda-flopy.yml"

matrix:
  allow_failures:
    - ENV_FILE: "ci/37-conda-flopy.yml"

  fast_finish: true  # terminate build on first error

platform:
    - x64

build: false

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\mfsetup'

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # set up environment
  - CALL "%MINICONDA%\\Scripts\\activate.bat"
  - conda config --set always_yes yes --set show_channel_urls true --set changeps1 no
  - conda update conda
  # this is basically equivalent to what conda init does.  It changes the "conda" to
  #    be a .bat script that sets appropriate PATH entries before conda hits problems.
  #  This PATH modification only works with conda 4.6+, but it won't hurt other versions.
  - set "PATH=%MINICONDA%\condabin:%PATH%"
  - conda info -a
  # free channel needed for older envs (< py37), see
  # https://github.com/conda/conda/issues/8849
  - conda config --set restore_free_channel true
  #- conda config --set always_yes yes --set changeps1 no
  - conda env create --file="${ENV_FILE}"
  # Show the installed packages + versions
  - conda list

test_script:
  - conda activate test
  - pip install -e .
  - python -m ipykernel install --user --name test --display-name "test"
  - pytest -v

after_test:
 - echo "done"
