name: mfsetup
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- scipy
- xarray
- netcdf4
- pandas
- geopandas
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- rtree
- pyproj
- pyshp
- pip
- pip:
  - git+git://github.com/modflowpy/flopy@develop
  - gis-utils
  - git+git://github.com/aleaf/modflow-export@develop
  - git+git://github.com/usgs/sfrmaker@develop
