simulation:
  sim_name: 'shellmound'
  version: 'mf6'
  sim_ws: 'model'

model:
  simulation: 'shellmound'
  modelname: 'shellmound'
  options:
    print_input: True
    save_flows: True
    newton: True
  packages: [
  ]

setup_grid:
  xoff: 501405 # lower left x-coordinate
  yoff: 1175835 # lower left y-coordinate
  nrow: 30
  ncol: 35
  dxy: 1000
  rotation: 0.
  epsg: 5070
  snap_to_NHG: True
