name: test
channels:
- conda-forge
- defaults
dependencies:
- python=3.*
- pyyaml
- numpy
- scipy
- xarray
- pandas
- gdal
- fiona
- rasterio=1.*
- shapely
- pyproj
- pyshp
- flopy
- codecov
- coverage
- flake8
- pytest
- sphinx
- ipython
- matplotlib
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
