name: test
channels:
- conda-forge
- defaults
dependencies:
- python=3.*
- pyyaml
- numpy
- scipy
- xarray
- netcdf4
- pandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx
- ipython
- matplotlib
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - https://github.com/modflowpy/flopy/zipball/develop
  - gis-utils
  - https://github.com/aleaf/sfrmaker/zipball/develop
