name: mfsetup_ci
channels:
- conda-forge
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy<2.1
- scipy
- xarray
- netcdf4
- pandas
- geopandas
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- rtree
- pyproj
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx=8.1.3
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - gis-utils
  - pytest-timeout
  - git+https://github.com/modflowpy/flopy@develop
  - git+https://github.com/aleaf/modflow-export@develop
  - git+https://github.com/usgs/sfrmaker@develop
