name: mfsetup_ci
channels:
- conda-forge
- defaults
- atleaf
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- jinja2==3.0
- matplotlib
- pyyaml
- numpy
- scipy
- xarray
- netcdf4
- pandas
- geopandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
  - git+https://github.com/aleaf/gis-utils@develop
  - git+https://github.com/modflowpy/flopy@develop
  - git+https://github.com/aleaf/modflow-export@develop
  - git+https://github.com/usgs/sfrmaker@develop
