name: Publish release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false

  docs:
    needs: release
    name: Publish Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Get latest release version number
      id: get_version
      uses: battila7/get-version-action@v2

    - name: Print version
      shell: bash
      run: |
        echo ${{ steps.get_version.outputs.version }}

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ci/test_environment.yaml
        cache-environment: false
        cache-downloads: false
        # persist on the same day.
        # cache-environment-key: environment-${{ steps.date.outputs.date }}
        # cache-downloads-key: downloads-${{ steps.date.outputs.date }}
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: >-
          bash

    - name: Conda info
      shell: bash -l {0}
      run: micromamba info
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        if [[ ! -d "$HOME/.local/bin" ]]; then
            mkdir -p "$HOME/.local/bin";
        fi
        # copy modflow bins to local dir to add to PATH later
        if [ "$RUNNER_OS" == "Windows" ]; then
            d="win"
        elif [ "$RUNNER_OS" == "macOS" ]; then
            d="mac"
        elif [ "$RUNNER_OS" == "Linux" ]; then
            d="linux"
        else
            d="unexpectedos"
            exit 1
        fi
        echo bin/$d/. >> $GITHUB_PATH
        echo $GITHUB_PATH
        pip install -e .
        python -m ipykernel install --user --name mfsetup_ci --display-name "mfsetup_ci"
    - name: Conda list
      shell: bash -l {0}
      run: micromamba list

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest mfsetup/test/test_notebooks.py

    - name: Build docs
      shell: bash -l {0}
      run: |
        set -e
        make -C docs html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
        CLEAN: false
        TARGET_FOLDER: ${{ steps.get_version.outputs.version }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.ALL_PROJECTS }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
