# Test that latest published versions can be installed & imported

name: Latest Release

on:
  schedule:
    - cron: '0 9 * * 1' # run every Monday at 9 AM UTC (3 am PST)
  workflow_dispatch:

jobs:
  build:
    name: Test Latest Releases
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Fetch all Git tags
      run: git fetch --prune --unshallow --tags
    - name: Get current date
      id: date
      run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ci/test_environment.yaml
        cache-environment: false
        cache-downloads: false
        # persist on the same day.
        # cache-environment-key: environment-${{ steps.date.outputs.date }}
        # cache-downloads-key: downloads-${{ steps.date.outputs.date }}
        create-args: >-
          python=${{ matrix.python-version }}
        init-shell: >-
          bash
    - name: Conda info
      shell: bash -l {0}
      run: micromamba info
    - name: Test install from github
      shell: bash -l {0}
      run: |
        pip install git+https://github.com/aleaf/modflow-setup@develop
        pytest mfsetup/tests/test_import.py
    - run: pip uninstall modflow-setup -y
    - name: Test install from pypi
      shell: bash -l {0}
      run: |
        pip install modflow-setup
        pytest mfsetup/tests/test_import.py
    - run: pip uninstall modflow-setup -y
    - name: Test install from conda
      shell: bash -l {0}
      run: |
        micromamba install modflow-setup
        pytest mfsetup/tests/test_import.py
    - run: micromamba remove modflow-setup --force
